config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions
  devise_for :users, controllers: { registrations: "my_devise/registrations" }
  resources :news, only: [:index, :show]
  namespace :mails do
    get :unsubscription
  end



  namespace :admin do
    get :dashboard, controller: 'dashboard'
    get :news_list, controller: 'dashboard'
    resources :categories
    resources :news
  end

  root 'news#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
 
  def dashboard
  end

  def news_list
    @news = News.order("created_at DESC")
  end

end

app/views/admin/dashboard/_instumental_panel.html.slim
.instr_panel
  .list-group
    - if Category.all.present?
      = link_to 'Добавить новость', new_admin_news_path, class: "list-group-item list-group-item-dark"
    = link_to 'Добавить категорию', new_admin_category_path, class: "list-group-item list-group-item-dark"
    = link_to 'Список пользователей', admin_dashboard_path, class: "list-group-item list-group-item-dark"
    = link_to 'Список новостей', admin_news_list_path, class: "list-group-item list-group-item-dark"
    = link_to 'Список категорий', admin_categories_path, class: "list-group-item list-group-item-dark"

app/views/admin/dashboard/_users_list.html.slim
table.table.table-sm
  thead.thead-light
    tr
      th[scope="col"]
        | Email
      th[scope="col"]
        | Подписка
      th[scope="col"]
        | Действия
  tbody
    - User.all.each do |user|
      tr
        th[width="60%"]
          = user.email
        td
          = t(user.subscription)
        td.links
          = link_to "Удалить аккаунт", user_registration_path(user), method: :delete, data: { confirm: 'Вы уверены' }

app/views/admin/dashboard/dashboard.html.slim
= render 'news/nav_bar'
= render 'instumental_panel'
.container
  .active_window
    = render 'users_list'

app/views/admin/dashboard/news_list.html.slim
= render 'news/nav_bar'
= render 'instumental_panel'
.container
  .active_window
    table.table.table-sm
      caption
        = button_to 'Добавить новость', new_admin_news_path, method:"get", class:"btn btn-success"
      thead.thead-light
        tr
          th[colspan="4" scope="col" style="text-align:center"]
            | Новости
      - @news.each do |n|
        tbody
          tr
            th[width="80%"]
              = n.title
            td.links
              = link_to 'Показать', admin_news_path(n)
            td.links
              = link_to 'Редактировать', edit_admin_news_path(n)
            td.links
              = link_to 'Удалить', admin_news_path(n), method: :delete, data: { confirm: 'Are you sure?' }