config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions
  devise_for :users, controllers: { registrations: "my_devise/registrations" }
  resources :news, only: [:index, :show]
  namespace :mails do
    get :unsubscription
  end



  namespace :admin do
    get :dashboard, controller: 'dashboard'
    get :news_list, controller: 'dashboard'
    resources :categories
    resources :news
  end

  root 'news#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/news.rb
class News < ApplicationRecord
    belongs_to :category
    validates :title, :text, presence: true
    validates :title, length: { maximum: 50 }
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < Admin::ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to admin_news_list_path, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to admin_news_list_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :text, :category_id)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show]

  # GET /news
  # GET /news.json
  def index
    @news = News.order("created_at DESC")
    if params[:filter]
      @news = News.where(category_id: params[:filter][:id]).order("created_at DESC")
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end
end

app/helpers/news_helper.rb
module NewsHelper
  def main_title
    if params[:controller] == 'news' && params[:action] == 'index' 
      'Газета, которую мы заслужили'
    else
      'На главную'
    end
  end
end

app/views/news/_nav_bar.html.slim
.container
  nav.navbar.fixed-top.navbar-dark.main_nav
    .nav_left
      a
        = link_to main_title, root_path, class:"navbar-brand"
    - if user_signed_in?
      .nav_right
        - if current_user.is_admin?
          .nav_admin_panel
            a
              = link_to 'Панель администратора', admin_dashboard_path, class:"navbar-brand"
        .nav_set_profile
          a
            = link_to 'Настройть профиль', edit_user_registration_path, class:"navbar-brand"
        .nav_sign_out
          a
            = link_to 'Выйти',  destroy_user_session_path, method: "delete", class:"navbar-brand"
    - else
      .nav_right
        .nav_right.nav_login
          a
            = link_to 'Зарегистрироваться', new_user_registration_path, class:"navbar-brand"
        .nav_right.nav_sign_in
          a
            = link_to 'Войти', new_user_session_path, class:"navbar-brand"

app/views/news/index.html.slim
= render 'news/nav_bar'
.cat_panel
  .list-group
    = link_to "Все новости", news_index_path, class: "list-group-item list-group-item-light"
    - Category.all.each do |c|
      = link_to c.title, news_index_path({filter: {id: c.id}}), class: "list-group-item list-group-item-light"
.content.container.col-2.col-md-7
  - @news.each do |news|
    - news.text.size > 300 ? text = news.text[0,600] : text = news.text
    .news
      .news_title
        h3
          = link_to news.title, news_url(news.id)
        h3

        hr
      .news_text
        p
          = text
          = link_to " читать далее", news_url(news.id), style: "color:#cd7f32;" if news.text.size > 600
        .links
          = link_to news.category.title, news_index_path({filter: {id: news.category.id}})

app/views/news/show.html.slim
= render 'news/nav_bar'
.content.container.col-2.col-md-8
  .show_content
    .show_title
      = @news.title
      hr
    .show_text
      = @news.text
      div
        = @news.category.title
      .links
        = link_to 'Назад', root_path