config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions
  devise_for :users, controllers: { registrations: "my_devise/registrations" }
  resources :news, only: [:index, :show]
  namespace :mails do
    get :unsubscription
  end



  namespace :admin do
    get :dashboard, controller: 'dashboard'
    get :news_list, controller: 'dashboard'
    resources :categories
    resources :news
  end

  root 'news#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :news, dependent: :destroy
    has_many :users, through: :subscriptions
    has_many :subscriptions, dependent: :destroy
    validates :title, presence: true, length: { maximum: 20 }, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: admin_categories_path }
      else
        format.html { render :new }
        format.json { render json: admin_categories_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: admin_categories_path }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.fetch(:category).permit(:title)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.slim
= form_with(model: [ :admin, category ], local: true) do |form|
  = render 'errors/error', object: category
  .field
    = form.label :title
    = form.text_field :title, class: "form-control"
    br
  .actions
    = form.submit class: "btn btn-success"

app/views/admin/categories/edit.html.slim
= render 'news/nav_bar'
= render 'admin/dashboard/instumental_panel'
.container
  .cat_form
    h2
      | Редактировать категорию
    = render 'form', category: @category

app/views/admin/categories/index.html.slim
= render 'news/nav_bar'
= render 'admin/dashboard/instumental_panel'
.container
  .active_window
    table.table.table-sm
      caption
        = button_to 'Добавить категорию', new_admin_category_path, method:"get", class:"btn btn-success"
      thead.thead-light
        tr
          th[colspan="3" scope="col" style="text-align:center"]
            | Категории
      - @categories.each do |category|
        tbody
          tr
            th[width="80%"]
              = category.title
            td.links
              = link_to 'Редактировать', edit_admin_category_path(category)
            td.links
              = link_to 'Удалить', admin_category_path(category), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/categories/new.html.slim
= render 'news/nav_bar'
= render 'admin/dashboard/instumental_panel'
.container
  .cat_form
    h2[align="center"]
      | Создать категорию
    = render 'form', category: @category