config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions
  devise_for :users, controllers: { registrations: "my_devise/registrations" }
  resources :news, only: [:index, :show]
  namespace :mails do
    get :unsubscription
  end



  namespace :admin do
    get :dashboard, controller: 'dashboard'
    get :news_list, controller: 'dashboard'
    resources :categories
    resources :news
  end

  root 'news#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/mail_sender/_news_view.html.slim
.digest[align="center"]
  .dig_title
    h1[style="color:#cd7f32"]
      | Газета, которую мы заслужили
  .dig_text
    h2
      = @p
  = @news.find_each do |news|
    - news.text.size > 250 ? text = news.text[0,250] : text = news.text
    .one_news
      .news_content[style="width: 600px; align:center"]
        p[style="text-align:left"]
          b
            i
              = news.title
              | . 
          = text
          = link_to "читать далее", news_url(news.id), style: "color:#cd7f32" if news.text.size > 250
  .unsubscribe[style="margin-top:150px"]
    |  Для того, чтобы отписаться от рассылки, перейдите по этой 
    = link_to "ссылке", mails_unsubscription_url(unsubscription_token: @user.unsubscription_token)

app/views/mail_sender/send_every_day.html.slim
- @p  = "Самое важное за последние сутки"
= render 'news_view', news: @news , p: @p

app/views/mail_sender/send_every_week.html.slim
- @p  = "Самое важное за последнюю неделю"
= render 'news_view', news: @news